apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-dev
  namespace: dev
  labels:
    app: discord-bot-dev
spec:
  replicas: 3  # 1 active, 2 standby
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: discord-bot-dev
  template:
    metadata:
      labels:
        app: discord-bot-dev
    spec:
      containers:
        - name: discord-bot
          image: yakoob19/discord-bot:dev-latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "development"
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token-dev
                  key: token
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          livenessProbe:
            exec:
              command: ["pgrep", "node"]
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 1
          readinessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - |
                  ACTIVE_PODS=$(kubectl get pods -n dev -l app=discord-bot-dev --field-selector=status.phase=Running | grep -v NAME | wc -l)
                  if [ "$ACTIVE_PODS" -lt "2" ]; then exit 0; else exit 1; fi
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 1
