apiVersion: apps/v1
kind: Deployment
metadata:
    name: discord-bot-dev
    namespace: default
    labels:
        app: discord-bot-dev
spec:
    replicas: 3 # 1 active, 2 standby
    selector:
        matchLabels:
            app: discord-bot-dev
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0 # Ensure no downtime
            maxSurge: 2
    template:
        metadata:
            labels:
                app: discord-bot-dev
        spec:
            containers:
                - name: discord-bot
                  image: yakoob19/discord-bot:season3-dev
                  imagePullPolicy: Always
                  env:
                      - name: NODE_ENV
                        value: "development"
                      - name: DISCORD_TOKEN
                        valueFrom:
                            secretKeyRef:
                                name: discord-token-dev
                                key: token
                  resources:
                      requests:
                          cpu: "100m"
                          memory: "128Mi"
                      limits:
                          cpu: "250m"
                          memory: "512Mi"
                  livenessProbe:
                      exec:
                          command: ["pgrep", "node"] # Check if Node.js is running
                      initialDelaySeconds: 5
                      periodSeconds: 3
                      timeoutSeconds: 2
                      failureThreshold: 1 # Restart pod immediately after failure
                  restartPolicy: Always # Ensures bot restarts on failure
